UPDATE "AdminUser"
SET "permissions" = ARRAY[
  'dashboard.view',
  'crm.read',
  'crm.notes',
  'crm.write',
  'kyc.approve',
  'kyc.view',
  'alerts.view',
  'alerts.manage',
  'risk.view',
  'risk.manage',
  'positions.view',
  'positions.manage',
  'queues.manage',
  'transactions.view',
  'deposits.approve',
  'withdrawals.approve',
  'email.send',
  'admin.users.manage',
  'settings.manage',
  'email.settings',
  'orders.view',
  'chat.view',
  'admin-users.manage',
  'copy.approve',
  'affiliate.manage',
  'audit.view',
  'treasury.view',
  'treasury.manage',
  'health.view',
  'readiness.view',
  'users.view',
  'users.manage',
  'dealingdesk.manage'
]::TEXT[]
WHERE "role" = 'SUPER_ADMIN';
