import { Prisma } from '@prisma/client';

export const accountSelect = {
  id: true,
  userId: true,
  type: true,
  name: true,
  accountNo: true,
  balance: true,
  equity: true,
  currency: true,
  status: true,
  isDefault: true,
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.AccountSelect;

export const transactionSelect = {
  id: true,
  userId: true,
  walletId: true,
  accountId: true,
  type: true,
  amount: true,
  asset: true,
  status: true,
  reference: true,
  metadata: true,
  approvedById: true,
  approvedAt: true,
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.TransactionSelect;

export const positionSelect = {
  id: true,
  userId: true,
  accountId: true,
  orderId: true,
  copiedFromTradeId: true,
  symbol: true,
  side: true,
  entryPrice: true,
  exitPrice: true,
  volume: true,
  contractSize: true,
  leverage: true,
  margin: true,
  marginUsed: true,
  liquidationPrice: true,
  pnl: true,
  status: true,
  openedAt: true,
  closedAt: true,
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.PositionSelect;

export const orderSelect = {
  id: true,
  userId: true,
  accountId: true,
  clientRequestId: true,
  type: true,
  side: true,
  symbol: true,
  volume: true,
  leverage: true,
  requestedPrice: true,
  executionPrice: true,
  sourceType: true,
  metadata: true,
  status: true,
  rejectionReason: true,
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.OrderSelect;
